config/routes.rb
Rails.application.routes.draw do
  resources :sciences
 root 'pages#home'
 get 'about' ,to: 'pages#about'
 #get 'chandu' ,to: 'name#home'
 resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/science.rb
class Science < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController
    def show
        @article = Article.find(params[:id])
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    def show
        @article = Article.find(params[:id])
    end
    def index
        @articles = Article.all
    end
    def new
    
    end
    def edit
        @article = Article.find(params[:id])
      end
    
      def create
        @article = Article.new(params.require(:article).permit(:title, :description))
        if @article.save
    @@ -22,4 +26,14 @@ def create
        end

    def create
       @article = Article.new(params[:article])                        
        if @article.save
            flash[:notice] = " Article was created sucessfully."
            redirectt_to @article
        else
            render 'new'
        end
    end  
end

app/controllers/name_controller.rb
class NameController < ApplicationController
    def name

    end
    def home 
        
    end
end

app/controllers/sciences_controller.rb
class SciencesController < ApplicationController
  before_action :set_science, only: %i[ show edit update destroy ]

  # GET /sciences or /sciences.json
  def index
    @sciences = Science.all
  end

  # GET /sciences/1 or /sciences/1.json
  def show
  end

  # GET /sciences/new
  def new
    @science = Science.new
  end

  # GET /sciences/1/edit
  def edit
  end

  # POST /sciences or /sciences.json
  def create
    @science = Science.new(science_params)

    respond_to do |format|
      if @science.save
        format.html { redirect_to science_url(@science), notice: "Science was successfully created." }
        format.json { render :show, status: :created, location: @science }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @science.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sciences/1 or /sciences/1.json
  def update
    respond_to do |format|
      if @science.update(science_params)
        format.html { redirect_to science_url(@science), notice: "Science was successfully updated." }
        format.json { render :show, status: :ok, location: @science }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @science.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sciences/1 or /sciences/1.json
  def destroy
    @science.destroy

    respond_to do |format|
      format.html { redirect_to sciences_url, notice: "Science was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_science
      @science = Science.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def science_params
      params.fetch(:science, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sciences_helper.rb
module SciencesHelper
end

app/views/articles/_form.html.erb
<%= form_with(model: article, local: true) do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<% if @article.errors.any? %>
  <h2>The following errors prevented the article from being saved</h2>
  <ul>
    <% @article.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>
<%= form_with(model: @article, local: true) do |f| %>

  <p>
    <%= f.label :title %><br/>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :description %><br/>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %> 

app/views/articles/index.html.erb
<h1>Articles listing pages</h1>

<%= @article %>

app/views/articles/new.html.erb
<h1>Create a New Article</h1>


<%= form_with scope: :article,url: articles_path, local: true do |f| %>


    <p>
    <%= f.label :title %><br/>
    <%= f.text_field :title %>
    </p>
    
    <p>
    <%= f.label :description %><br/>
    <%= f.text_area :description %>
    </p>
    
    <p>
    <%= f.submit %>
    </p>
 <% end %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @article.description %>
</p>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/pages/home.html.erb
<h1> This is a home page</h1>

app/views/pages/index.html.erb
<h1>Showing articles details</h1>


<p><strong>Title: </strong><%= @articles.%></p>

app/views/sciences/_form.html.erb
<%= form_with(model: science) do |form| %>
  <% if science.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(science.errors.count, "error") %> prohibited this science from being saved:</h2>

      <ul>
        <% science.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/sciences/_science.html.erb
<div id="<%= dom_id science %>">
</div>

app/views/sciences/edit.html.erb
<h1>Editing science</h1>

<%= render "form", science: @science %>

<br>

<div>
  <%= link_to "Show this science", @science %> |
  <%= link_to "Back to sciences", sciences_path %>
</div>

app/views/sciences/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Sciences</h1>

<div id="sciences">
  <% @sciences.each do |science| %>
    <%= render science %>
    <p>
      <%= link_to "Show this science", science %>
    </p>
  <% end %>
</div>

<%= link_to "New science", new_science_path %>

app/views/sciences/new.html.erb
<h1>New science</h1>

<%= render "form", science: @science %>

<br>

<div>
  <%= link_to "Back to sciences", sciences_path %>
</div>

app/views/sciences/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @science %>

<div>
  <%= link_to "Edit this science", edit_science_path(@science) %> |
  <%= link_to "Back to sciences", sciences_path %>

  <%= button_to "Destroy this science", @science, method: :delete %>
</div>